services:
  web:
    build: .
    container_name: onlypings_backend
    ports:
      - "8000:8000"
    volumes:
      # ეს ხაზი ამბობს: "ჩემი მიმდინარე საქაღალდე (.) იყოს დოკერის მთავარი საქაღალდე (/app)"
      - .:/app
      # ეს ძველი ხაზი შეგიძლია დატოვო, ან წაშალო, რადგან ზედა ხაზი უკვე ყველაფერს მოიცავს
      - ./onlypings_data:/app/data
    restart: always